apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: appsso-starter-java
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: appsso-starter-java
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/live-update: "true"
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/version: 2.6.6
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          developer-conventions/live-update-convention
          developer-conventions/add-source-image-label
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
        developer.apps.tanzu.vmware.com/image-source-digest: main/642d6538a4fd4c7e47d5cf26d20df2827b49f2ee
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: appsso-starter-java
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: appsso-starter-java
        conventions.apps.tanzu.vmware.com/framework: spring-boot
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.health.probes.enabled="true" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: gcr.io/cf-identity-service-oak/pdx/appsso-starter-java-workloads@sha256:00a4f726f48bf1bf47555cacb6b1bd8427e7e8671d5d904d37fcd7611cd91062
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

